server:
  type: simple
  applicationConnectors: /
  adminContextPath: /admin
  connector:
    type: http
    port: 5000

db:
  driverClass: org.postgresql.Driver
  user: ${POSTGRES_USER:-marquez}
  password: ${POSTGRES_PASSWORD:-change-me}
  url: jdbc:postgresql://db:5432/${POSTGRES_DB:-marquez}

# CORS (UI가 별도 포트/호스트에서 접근 시)
cors:
  enabled: true
  allowedOrigins: ${CORS_ALLOWED_ORIGINS:-*}
  allowedMethods: [GET, POST, PUT, DELETE, OPTIONS]
  allowedHeaders: ["*"]

logging:
  level: INFO
  appenders:
    - type: console
      threshold: INFO