server:
  applicationConnectors:
    - type: http
      port: 5000
  adminConnectors: []   # (옵션) admin 포트 안 쓰면 빈 배열

db:
  driverClass: org.postgresql.Driver
  url: jdbc:postgresql://pg:5432/marquez
  user: marquez
  password: marquez

# (권장) 기동 시 자동 마이그레이션
migrateOnStartup: true

logging:
  level: INFO
  appenders:
    - type: console
      threshold: INFO